server:
  port: 8082
  address: 0.0.0.0

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://***:3306/ruangong?serverTimezone=GMT%2b8&characterEncoding=utf-8
      username: ***
      password: ***
  devtools:
    livereload:
      enabled: true
  redis:
    host: ***
    password: ***
    port: 6379
    database: 3
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

wechat:
  AppID: ***
  AppSecret: ***

esc:
  ip: ***
  username: ***
  password: ***!
  picture:
    port: 80
    path: /home/images
